spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/droffice
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
    .show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  freemarker:
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    template-loader-path: classpath:/templates/
    settings:
      object_wrapper: DefaultObjectWrapper(2.3.25, exposeFields = true)